version: '2'
services:
  bamboo:
    image: sxmichael/docker-bamboo-server
    environment:
      X_PROXY_NAME: bamboo.objektarium.de
      X_PROXY_PORT: '443'
      X_PROXY_SCHEME: https
      X_PROXY_PATH: /
      BAMBOO_VERSION: 6.4.0
    stdin_open: true
    volumes:
    - /srv/bamboo/data:/var/atlassian/bamboo
    - /srv/bamboo/logs:/opt/atlassian/bamboo/logs
    - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: lb=true
  bamboo-agent:
    image: marsmike/bamboo-docker-agent:1.0.0
    environment:
      BAMBOO_SERVER: https://bamboo.objektarium.de/
      HOME: /root/
    stdin_open: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    labels:
      io.rancher.container.pull_image: always
