version: '2'
services:
  public-HTTPS:
    scale: 1
    start_on_create: true
    lb_config:
      certs:
      - bamboo.objektarium.de
      - confluence.objektarium.de
      - jira.objektarium.de
      - bitbucket.objektarium.de
      - webdav.objektarium.de
      - jenkins.objektarium.de
      - teamcity.objektarium.de
      - gitlab.objektarium.de
      - cloud.objektarium.de
      default_cert: zeus.objektarium.de
      port_rules:
      - hostname: bitbucket.objektarium.de
        path: ''
        priority: 1
        protocol: https
        service: bitbucket/bitbucket-server
        source_port: 443
        target_port: 7990
      - hostname: jira.objektarium.de
        path: ''
        priority: 2
        protocol: https
        service: jira/jira-server
        source_port: 443
        target_port: 8080
      - hostname: bamboo.objektarium.de
        priority: 3
        protocol: https
        service: bamboo/bamboo
        source_port: 443
        target_port: 8085
      - hostname: cloud.objektarium.de
        path: ''
        priority: 4
        protocol: https
        service: postgresql/adminer
        source_port: 443
        target_port: 8080
      - hostname: zeus.objektarium.de
        path: ''
        priority: 5
        protocol: https
        service: nginx-hello
        source_port: 443
        target_port: 80
      - hostname: gitlab.objektarium.de
        path: ''
        priority: 6
        protocol: https
        service: bitbucket/bitbucket-server
        source_port: 443
        target_port: 7990
      - hostname: webdav.objektarium.de
        path: ''
        priority: 7
        protocol: https
        service: postgresql/adminer
        source_port: 443
        target_port: 8080
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  https-redirect:
    start_on_create: true
  public-HTTP:
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: /.well-known/
        priority: 2
        protocol: http
        service: rancher-lets-encrypt/letsencrypt-nginx
        source_port: 80
        target_port: 80
      - priority: 3
        protocol: http
        service: https-redirect
        source_port: 80
        target_port: 80
      - priority: 4
        protocol: tcp
        service: bitbucket/bitbucket-server
        source_port: 7999
        target_port: 7999
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  nginx-hello:
    scale: 1
    start_on_create: true
